-- DDL - Data Definition Language - CREATE, ALTER, DROP, TRUNCATE

-- CREATE TABLE
CREATE TABLE STUD(
    ID NUMBER(5) PRIMARY KEY,
    NAME VARCHAR(10),
    CITY VARCHAR(10)
);


-- ALTER TABLE ->(Add new col, modify existing col, rename a col, drop a col)
ALTER TABLE STUD ADD MOB NUMBER(10);
ALTER TABLE STUD ADD(DNO NUMBER(10), DEP VARCHAR(10));

ALTER TABLE STUD MODIFY MOB NUMBER(20);
ALTER TABLE STUD MODIFY(MOB CHAR(10), DEP VARCHAR(100));

ALTER TABLE STUD RENAME COLUMN DNO TO SNO;

ALTER TABLE STUD DROP COLUMN SNO;
ALTER TABLE STUD DROP (MOB, DEP);



SELECT * FROM STUD;
DESC STUD;

CREATE TABLE DOCTOR(
    DOCTOR_ID NUMBER(5) PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    SPECIALITY VARCHAR(100),
    EMAIL VARCHAR(100),
    PHONE_NUMBER VARCHAR(20),
    ADDRESS VARCHAR(255)
);

SELECT * FROM DOCTOR;

-- DROP TABLE
DROP TABLE DOCTOR;
DROP TABLE DOCTOR PURGE; -- DELETES FROM RECYCLE BIN

-- TRUNCATE TABLE
CREATE TABLE CUSTOMER(ID NUMBER(5), NAME VARCHAR(10));
SELECT * FROM CUSTOMER;
TRUNCATE TABLE CUSTOMER; -- DELETES DATA NOT TABLE


ALTER TABLE STUD ADD MOB NUMBER(10);
ALTER TABLE STUD MODIFY CITY VARCHAR(20);

-- DML - Data Manipulation Language(SELECT, INSERT, UPDATE, DELETE)
INSERT INTO STUD(ID, NAME, CITY, MOB) VALUES (1, 'John', 'New York', 1234567890);
INSERT INTO STUD(ID, NAME, CITY, MOB) VALUES (2, 'Alice', 'Los Angeles', 9876543210);
INSERT INTO STUD(ID, NAME, CITY, MOB) VALUES (3, 'Bob', 'Chicago', 5555555555);
INSERT INTO STUD(ID, NAME, CITY, MOB) VALUES (4, 'Eva', 'San Francisco', 7777777777);
INSERT INTO STUD(ID, NAME, CITY, MOB) VALUES (5, 'Mike', 'Houston', 1234555671);

-- SELECT
SELECT * FROM STUD;
SELECT NAME, CITY FROM STUD;
SELECT * FROM STUD WHERE ID = 2;
SELECT * FROM STUD WHERE CITY = 'Chicago';
SELECT * FROM STUD WHERE ID IN (1, 2, 3);

-- UPDATE
UPDATE STUD SET NAME = 'July' WHERE ID = 1;

-- DELETE (Can specificaly delete particular rows based on condition)
DELETE STUD WHERE ID = 2;
DELETE FROM STUD WHERE ID = 5;
-- DELETE STUD;
-- DELETE FROM STUD;

-- TCL - Transaction Control Language (COMMIT, ROLLBACK)
COMMIT;
ROLLBACK;

